spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/mymsn
    username: mymsn
    password: mymsn
  # Liquibase use by default settings of datasource
  liquibase:
    change-log: db/master.xml
mail:
  host: smtp.mailgun.org
  port: 587
  username: postmaster@sandboxb1336a3eae784c92b3c5a9b10da17989.mailgun.org
  password: 319a3de82890b7a10ba2bf3919944668-6ae2ecad-0e1c657e
  enablettls: true
  auth: true
  frommail: vicosenderprod@yopmail.com
configuration:
  baseUrl: http://localhost:4300
