spring:
  profiles:
    # @spring.profiles.active@ get value define in properties from pom.xml define by the maven profile used
    active: @spring.profiles.active@
security:
  ignored: /**
configuration:
  secret: "asdfSFS34wfsdfsdfSDSD32dfsddDDerQSNCK34SOWEK5354fdgdf4"
  # Time before a reset password link is invalid (in minutes)
  expirationlinktime: 60
