spring:
  # Liquibase use by default settings of datasource in resources file
  datasource:
    url: jdbc:postgresql://localhost:5432/mymsn
    username: mymsn
    password: mymsn
  liquibase:
    change-log: db/master.xml
mail:
  host: 127.0.0.1
  port: 1025
  username:
  password:
  enablettls: false
  auth: false
  frommail: vicosenderdev@yopmail.com
configuration:
  baseUrl: http://localhost:4200
