spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/mymsn
    username: mymsn
    password: mymsn
  # Liquibase use by default settings of datasource
  liquibase:
    change-log: db/master.xml
mail:
  host: # SMTP host
  port: # SMTP Port
  username: # Username
  password: # Passeword
  enablettls: true
  auth: true
  frommail: # Email address which will send email
configuration:
  baseUrl: # URL of the apps
