import { Observable } from 'rxjs';
import { Injectable } from '@angular/core';
import { HttpClient } from '@angular/common/http';
import { environment } from 'src/environment/environment';
import { Router } from '@angular/router';

@Injectable({ providedIn: 'root' })
export class AccountService {
  private http: HttpClient;
  private router: Router;

  constructor(http: HttpClient, router: Router) {
    this.http = http;
    this.router = router;
  }

  public login(login: string, password: string): Promise<any> {
    return new Promise((resolve, reject) => {
      this.http
        .post<{ token: string }>(`${environment.apiUrl}/login`, {
          login,
          password,
        })
        .subscribe({
          next: (res) => {
            // Saving token generated by backend
            localStorage.setItem('token', res.token);
            resolve(undefined);
          },
          error: (error: Error) => {
            reject(error);
          },
        });
    });
  }

  public logout(): void {
    // Clearing localStorage
    localStorage.clear();
    // Redirecting to login page
    this.router.navigate(['/']);
  }
}
